version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - echo Prep the environment
      - echo beginning build
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python3 get-pip.py
      - pip install --upgrade pip
      - pip install taskcat
      - pip install "setuptools<82"

  build:
    commands:
      - taskcat test run
  post_build:
    commands:
      - aws s3 cp --recursive  ./taskcat_outputs s3://pipeline-taskcat-sitebucket-w8patwbzatab/
artifacts:
  type: zip
  files:
    - ./index.html